-- Connexion SYS
CONN / AS SYSDBA;

-- Création PDB
CREATE PLUGGABLE DATABASE hotel_pdb
ADMIN USER hotel_admin IDENTIFIED BY hotel123
FILE_NAME_CONVERT=('pdbseed','hotel_pdb');

ALTER PLUGGABLE DATABASE hotel_pdb OPEN;

ALTER SESSION SET CONTAINER = hotel_pdb;

-- Tablespaces
CREATE TABLESPACE hotel_data
DATAFILE 'hotel_data01.dbf'
SIZE 500M AUTOEXTEND ON;

CREATE TABLESPACE hotel_index
DATAFILE 'hotel_index01.dbf'
SIZE 200M AUTOEXTEND ON;

-- Users
CREATE USER manager IDENTIFIED BY manager123
DEFAULT TABLESPACE hotel_data
TEMPORARY TABLESPACE temp;

CREATE USER reception IDENTIFIED BY reception123
DEFAULT TABLESPACE hotel_data
TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE TABLE TO manager;
GRANT CREATE SESSION TO reception;

ALTER USER manager QUOTA UNLIMITED ON hotel_data;
ALTER USER reception QUOTA 200M ON hotel_data;